### ISSUE TITLE
Digital Ocean plugin unstable (dobs)

### ISSUE THREAD

**Issue by patrickleet** [thecodeteam/rexray#1002]
# Summary
I've been using the dobs plugin for rexray for a couple of months, and frequently, the volume gets disconnected and never reconnects

# Bug Reports
This section is for issues that relate to discovered problems or bugs.

## Version

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 9c7b7329884bf2feeffe101fc5dc3a239730427d
Formed: Wed, 28 Jun 2017 20:09:01 UTC

libStorage
----------
SemVer: 0.6.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 7368564cc71be9a0dbe03ddfbaeda281232eee72
Formed: Wed, 28 Jun 2017 20:08:31 UTC
```

## Expected Behavior
If a container is running on the same node for weeks, the volume should continue to be accessible and not disconnect

If a container gets rescheduled, the volume should be attached to the new node

## Actual Behavior
The volume becomes unavailable and the only way to fix is detaching the volume, removing the service that relies on it, and redeploying the service

## Steps To Reproduce
Use Rexray and dobs plugin for a couple weeks

## Configuration Files

```yaml
libstorage:
  service: dobs
  server:
    services:
      dobs:
        driver: dobs
        dobs:
          token: xxx
          region: nyc1
          tag: rexray
          convertUnderscores: true
          statusMaxAttempts: 10
          statusInitialDelay: 100ms
```

```
$ docker stack ps --no-trunc proxy

ID                          NAME                IMAGE                                                                                                      NODE                DESIRED STATE       CURRENT STATE             ERROR               PORTS
j7jw8eiu7zex7cnd9hevotykj    \_ proxy_proxy.1   vfarcic/docker-flow-proxy:latest@sha256:598f4ae2eb4a00a044ecf79e263a953b2acb034cb827cd4ffe2d9637c9787951   swarm-worker-02     Shutdown            Rejected 24 minutes ago   "VolumeDriver.Mount: {"Error":"resource not found"}
"                           
7sa8j17548dm0ifl9m9rqngy1    \_ proxy_proxy.1   vfarcic/docker-flow-proxy:latest@sha256:598f4ae2eb4a00a044ecf79e263a953b2acb034cb827cd4ffe2d9637c9787951   swarm-worker-02     Shutdown            Rejected 24 minutes ago   "VolumeDriver.Mount: {"Error":"resource not found"}
"                           
5uymxo3e2wzkctaheoel0790p    \_ proxy_proxy.1   vfarcic/docker-flow-proxy:latest@sha256:598f4ae2eb4a00a044ecf79e263a953b2acb034cb827cd4ffe2d9637c9787951   swarm-worker-02     Shutdown            Rejected 24 minutes ago   "VolumeDriver.Mount: {"Error":"resource not found"}
"                           
qgjsbm3w8rcntp32rzgavu0p6    \_ proxy_proxy.1   vfarcic/docker-flow-proxy:latest@sha256:598f4ae2eb4a00a044ecf79e263a953b2acb034cb827cd4ffe2d9637c9787951   swarm-worker-02     Shutdown            Rejected 24 minutes ago   "VolumeDriver.Mount: {"Error":"resource not found"}
```

**Comment by dave08** [comment]
Try something like:
```
libstorage:
  service: dobs
  integration:
    volume:
      operations:
        create:
          default:
            size: 1
        mount:
          preempt: true
        unmount: 
          ignoreUsedCount: true
dobs:
  region: fra1
```

Worked for me...
