### ISSUE TITLE
libstorage: error finding system in rexray + scaleio environment 

### ISSUE THREAD

**Issue by itot555** [thecodeteam/rexray#1081]
# Summary
Rexray service couldn't start in scaleio environment.
So, is there wrong setting ?

# Rexray version
```shell
# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0
OsArch: Linux-x86_64
Commit: 508023f4b0e4974f1844c26b39af7c4219f4c7a9
Formed: Mon, 16 Oct 2017 16:07:06 JST
```
# Rexray configuration file
I created rexray configuration file such as /etc/rexray/config.yml

```yaml
libstorage:
  # The libstorage.service property directs a libStorage client to direct its
  # requests to the given service by default. It is not used by the server.
  service: scaleio
  server:
   services:
    scaleio:
     driver: scaleio
     scaleio:
      endpoint:             https://scaleio_gateway_ip/api
      #apiVersion:           "2.0"
      insecure:             true
      #useCerts:             true
      userName:             admin
      password:             xxxxx
      systemID:             xxxxx
      protectionDomainID:   xxxxx
      protectionDomainName: pd01
      storagePoolID:        xxxxx
      storagePoolName:      sp01
      thinOrThick:          ThinProvisioned
```

# Rexray debug log when starting
``` Logs
# rexray start -f -l debug
INFO[0000] configured default CSI module                 CSI_ENDPOINT=/run/docker/plugins/rexray.sock time=1508748316498
INFO[0000] DockerLegacyMode                              enabled=false time=1508748316498
DEBU[0000] trapped signals                               time=1508748316498
DEBU[0000] loading config                                buildType=client+agent+controller configFileName=rexray globalConfigFileExists=false globalConfigFilePath=/etc/rexray/rexray.yml ignoreExists=false time=1508748316498 userConfigFileExists=false userConfigFilePath=/root/.rexray/rexray.yml
DEBU[0000] cannot find global or user file               buildType=client+agent+controller configFileName=rexray globalConfigFileExists=false globalConfigFilePath=/etc/rexray/rexray.yml ignoreExists=false time=1508748316498 userConfigFileExists=false userConfigFilePath=/root/.rexray/rexray.yml
DEBU[0000] loading config                                buildType=client+agent+controller configFileName=config globalConfigFileExists=true globalConfigFilePath=/etc/rexray/config.yml ignoreExists=true time=1508748316498 userConfigFileExists=false userConfigFilePath=/root/.rexray/config.yml
DEBU[0000] disabled config file exist check              buildType=client+agent+controller configFileName=config globalConfigFileExists=true globalConfigFilePath=/etc/rexray/config.yml ignoreExists=true time=1508748316498 userConfigFileExists=false userConfigFilePath=/root/.rexray/config.yml
DEBU[0000] validating global config                      buildType=client+agent+controller configFileName=config globalConfigFileExists=true globalConfigFilePath=/etc/rexray/config.yml ignoreExists=true time=1508748316498 userConfigFileExists=false userConfigFilePath=/root/.rexray/config.yml
DEBU[0000] created new config                            buildType=client+agent+controller configFileName=config globalConfigFileExists=true globalConfigFilePath=/etc/rexray/config.yml ignoreExists=true time=1508748316499 userConfigFileExists=false userConfigFilePath=/root/.rexray/config.yml
DEBU[0000] initializing configuration
DEBU[0000] loading yaml for Global
DEBU[0000] loading yaml for CSI
DEBU[0000] loading global config file                    path=/etc/rexray/config.yml
DEBU[0000] usage template path                           path=/root/.rexray/usage.template time=1508748316502
DEBU[0000] loaded usage template                         source=UsageTemplate time=1508748316502
DEBU[0000] updating log level                            level=debug time=1508748316503
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] created scoped scope                          new=rexray.cli parentScopes=rexray,
DEBU[0000] os.args                                       time=1508748316510 val=[rexray start -f -l debug]
DEBU[0000] host is empty; initiliazing default services  time=1508748316523
DEBU[0000] libStorage auto service mode disabled; services defined  time=1508748316526
DEBU[0000] starting embedded libStorage server           time=1508748316526
DEBU[0000] created scoped scope                          new=libstorage.server parentScopes=rexray.cli,rexray,
INFO[0000] configured logging                            libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=debug server=glow-glass-pw time=1508748316623
DEBU[0000] parsed server auth property                   libstorage.server.auth.disabled=false server=glow-glass-pw time=1508748316650
DEBU[0000] parsed server auth property                   libstorage.server.auth.key= server=glow-glass-pw time=1508748316665
DEBU[0000] parsed server auth property                   libstorage.server.auth.alg=HS256 server=glow-glass-pw time=1508748316678
DEBU[0000] parsed server auth property                   libstorage.server.auth.allow=[] server=glow-glass-pw time=1508748316694
DEBU[0000] parsed server auth property                   libstorage.server.auth.deny=[] server=glow-glass-pw time=1508748316710
INFO[0000] configured global auth                        libstorage.server.auth.alg=HS256 libstorage.server.auth.allow=[] libstorage.server.auth.deny=[] libstorage.server.auth.disabled=false libstorage.server.auth.key= server=glow-glass-pw time=1508748316710
INFO[0000] initializing server                           server=glow-glass-pw time=1508748316710
INFO[0000] initializing server services                  server=glow-glass-pw time=1508748316710
DEBU[0000] configured result schema validation           enabled=false server=glow-glass-pw time=1508748316715
DEBU[0000] got services map                              count=1 server=glow-glass-pw time=1508748316721
DEBU[0000] processing service config                     server=glow-glass-pw service=scaleio time=1508748316721
DEBU[0000] getting scoped config for service             scope=libstorage.server.services.scaleio server=glow-glass-pw service=scaleio time=1508748316721
DEBU[0000] created scoped scope                          new=libstorage.server.services.scaleio parentScopes=libstorage.server,rexray.cli,rexray,
DEBU[0000] got driver name                               driverName=scaleio server=glow-glass-pw service=scaleio time=1508748316732
DEBU[0000] starting scaleio driver                       endpoint=https://xxxxx/api insecure=true provider=scaleIO useCerts=false
DEBU[0000] err: problem getting instances: error decoding instances response: flate: corrupt input before offset 5  endpoint=https://xxxxx/api insecure=true provider=scaleIO systemId=xxxxx systemName= useCerts=false
INFO[0000] service shutdown complete                     time=1508748316989
error: service startup failed: libstorage: error finding system
```
