### ISSUE TITLE
REX-Ray 0.11.0 doesn't start on machines w/o docker w/o special config

### ISSUE THREAD

**Issue by codenrhoden** [thecodeteam/rexray#1108]
# Summary
I think this is a change as of 0.11.0 since we created the CSI module backend, but if you try to start REX-Ray on a machine without Docker installed, it fails unless you specify a custom `CSI_ENDPOINT`. I'm not sure this is by design.

# Bug Reports

## Version

```shell
# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0
OsArch: Linux-x86_64
Commit: 508023f4b0e4974f1844c26b39af7c4219f4c7a9
Formed: Mon, 16 Oct 2017 00:07:06 PDT
```

## Expected Behavior
Be able to start REX-Ray with minimal config, even w/o Docker installed

## Actual Behavior
REX-Ray fails to start with: `error: service startup failed: agent: mod start failed: invalid implied sock file: /run/docker/plugins/rexray.sock: open /run/docker/plugins/rexray.sock: no such file or directory`

## Steps To Reproduce

`rexray start` will make things fail because it tries to create the `.sock` file in `/var/run/docker` which does not exist. Setting `CSI_ENDPOINT` to a valid path makes it work: `CSI_ENDPOINT=/var/run/rexray/csi.sock rexray start`

## Configuration Files

I was using a ScaleIO system at the time:

```yaml
rexray:
  logLevel: debug
libstorage:
  service: scaleio
scaleio:
  insecure: true
  thinOrThick: ThinProvisioned
  endpoint: https://10.50.10.200:443/api
  userName: admin
  password: ****
  systemName: scaleio
  protectionDomainName: default
  storagePoolName: default
```

## Logs
https://gist.github.com/codenrhoden/08b00b4258f03f6d79362365b7cb89bc
