### ISSUE TITLE
Not able to connect to cinder v2 or v3

### ISSUE THREAD

**Issue by DukeyToo** [thecodeteam/rexray#1113]
# Summary
My openstack environment is running cinder v2 and v3.  When I try to start rexray, I get error `error: service startup failed: libstorage: error getting newBlockStorageV1`

# Bug Reports
I think I am hitting the first error from this code:
```
        if d.clientBlockStorage, err = openstack.NewBlockStorageV1(d.provider, endpointOpts); err != nil {
		return goof.WithFieldsE(fields, "error getting newBlockStorageV1", err)
	}

	d.clientBlockStoragev2, err = openstack.NewBlockStorageV2(d.provider, endpointOpts)
	if err != nil {
		// fallback to volume v1
		context.WithFields(fields).Info("BlockStorage API V2 not available, fallback to V1")
		d.clientBlockStoragev2 = nil
	}
```

## Version

```shell
$ rexray version
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] created scoped scope                          new=rexray.cli parentScopes=rexray,
DEBU[0000] os.args                                       time=1510847252431 val=[rexray version]
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0
OsArch: Linux-x86_64
Commit: 508023f4b0e4974f1844c26b39af7c4219f4c7a9
Formed: Mon, 16 Oct 2017 07:07:06 UTC
DEBU[0000] completed cli execution                       time=1510847252431
INFO[0000] exiting process                               time=1510847252431
DEBU[0000] completed onExit at end of program            time=1510847252431
```

## Expected Behavior
When cinder block storage v1 is not available, v2 or v3 should be used.

## Actual Behavior
When cinder block storage v1 is not available, rexray will not work.

## Steps To Reproduce
Configure rexray to connect to cinder on an openstack environment where cinder v1 is not available (v2 and v3 should be available).

Attempt to start rexray service or run rexray shell command to list volumes, e.g. `rexray volume ls`.  

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```yaml
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
    httpRequests:  true
    httpResponses: true
  service: cinder
  server:
    services:
      cinder:
        driver: cinder
  integration:
    volume:
      operations:
        create:
          default:
            size: 2
        mount:
          preempt: true
cinder:
  userName: ****
  password: ****
  regionName: ****
  authURL: https://****:5000/v3
  domainName: ***
  tenantID: ***
  tenantName: ***
```

## Logs

https://gist.github.com/DukeyToo/f8e1493971ee5b8d33657b31326c45a3
