### ISSUE TITLE
convertUnderscores for s3fs?

### ISSUE THREAD

**Issue by khoanguyen96** [thecodeteam/rexray#1120]
# Summary

Hey,

I noticed how there were options to convertUnderscores for GCE and DO, it would be nice to have it for Amazon as well?

# New Feature

`convertUnderscores` option for Amazon? specifically for S3...

## Version

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0
OsArch: Linux-x86_64
Commit: 508023f4b0e4974f1844c26b39af7c4219f4c7a9
Formed: Mon, 16 Oct 2017 00:07:06 PDT
```

## Configuration Files

```yaml
libstorage:
  service: s3fs
s3fs:
  accessKey: XXXX
  secretKey: XXXX
  endpoint: https://play.minio.io
  region: us-east-1
  disablePathStyle: false
  options:
    - url=https://play.minio.io
    - use_path_request_style
    - allow_other
    - nonempty
```
