### ISSUE TITLE
Mountpoints stays mounted after rexray detaches volume

### ISSUE THREAD

**Issue by popopanda** [thecodeteam/rexray#1130]
# Summary
I'm doing a POC with rexray in a mesos environment to provide persistent storage via EBS to our docker containers. Containers are launched through marathon, in my example, I have a nginx container that is launched and mounts a volume to `/data/www` with `/var/lib/rexray/docker/volumes/nginx` on the host

Problem occurs when containers are restarted in marathon, and if containers are reran on the same hosts, it will error

# Bug Reports

## Version
```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0
OsArch: Linux-x86_64
Commit: 508023f4b0e4974f1844c26b39af7c4219f4c7a9
Formed: Mon, 16 Oct 2017 07:07:06 UTC
```
```
Mesos cluster - v1.3.0
```
```
Docker:
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

## Expected Behavior
Remount volumes to hosts without read/write issues

## Actual Behavior
Rexray is unable to remount volumes on mesos slaves because volumes are not unmounted, even though volumes are detached

## Steps To Reproduce
In my test setup, I have 2 slaves (Slave_A and Slave_B), both in us-east-1b, and I can launch the container. Rexray will proceed on creating an ebs volume, and attach it to the host. In this case, the slave is Slave_A. I can confirm this via `df -h` on Slave_A

```
/dev/xvdp        50G   53M   47G   1% /var/lib/rexray/docker/volumes/nginx
```

This is working perfectly. When I proceed to restart the task in marathon, and the container is recreated on Slave_B, it will also take the same EBS volume, and mount it on Slave_B. I can confirm this again by `df -h`

```
/dev/xvdj        50G   53M   47G   1% /var/lib/rexray/volumes/nginx
```

The problem occurs when I look at Slave_A again via `mounts`, `fdisk`, or `df -h` commands, the OS still believes the volume is still mounted. This causes problems when I restart the nginx task in marathon once more, and the container will "hang" while trying to recreate itself in Slave_A. 

The logs will tell me:
```
returned error: error while mounting volume '/': VolumeDriver.Mount: NodePublishVolume failed: 6: mount failed: exit status 32\nmounting arguments: -o remount /var/lib/rexray/volumes/nginx/data /var/lib/rexray/docker/volumes/nginx\noutput: mount: cannot remount /var/lib/rexray/volumes/nginx/data read-write, is write-protected\n"
```

However, if I manually unmount `/dev/xvdp` on Slave_A before restarting the nginx job in marathon, the container will be created on Slave_A, and the ebs volume will be remounted on Slave_A perfectly.

## Configuration Files

```yaml
rexray:
  storageDrivers:
  - ec2
libstorage:
  service: ebs
  integration:
    volume:
      operations:
        create:
          default:
            size: 50
        mount:
          preempt: true
          rootPath: /data
        remove:
          force: false
        unmount:
          ignoreUsedCount: true
ebs:
  accessKey: test
  secretKey: testy
  region: us-east-1
```

### Service Log
No rexray logs

### Client Log
```
Dec 12 01:27:35:070135 Slave_A rexray: time="2017-12-12T01:27:35Z" level=error msg="mount Failed" args="-o remount /var/lib/rexray/volumes/nginx/data /var/lib/rexray/docker/volumes/nginx" cmd=mount error="exit status 32" output="mount: cannot remount /var/lib/rexray/volumes/nginx/data read-write, is write-protected\n"
```
