### ISSUE TITLE
Docker Swarm and DOBS volume must be unique error

### ISSUE THREAD

**Issue by dave08** [thecodeteam/rexray#1156]
# Summary
Hi! I have a Docker Swarm running on Digital Ocean w/ Rexray 0.11.0, and I'm constantly getting `"create prometheus: found reference to volume 'prometheus' in driver 'rexray', but got an error while checking the driver: error while checking if volume "prometheus" exists in driver "rexray": Post http://%2Frun%2Fdocker%2Fplugins%2Frexray.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rexray.sock: connect: connection refused: volume name must be unique" ` errors... as soon as any service fails, its very hard to get it back up and running...

There is only ONE volume called prometheus in block storage list... I also checked on the nodes, and there is no local prometheus volume either.

## Version
On master nodes:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 9c7b7329884bf2feeffe101fc5dc3a239730427d
Formed: Wed, 28 Jun 2017 20:09:01 UTC
  
libStorage
----------
SemVer: 0.6.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 7368564cc71be9a0dbe03ddfbaeda281232eee72
Formed: Wed, 28 Jun 2017 20:08:31 UTC

```
On worker nodes:
```shell
root@swarm-03:~# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0
OsArch: Linux-x86_64
Commit: 508023f4b0e4974f1844c26b39af7c4219f4c7a9
Formed: Mon, 16 Oct 2017 07:07:06 UTC
```

## Expected Behavior
Succeed in mounting the storage to the container

## Actual Behavior
Above error, and container constantly failing to go up, docker tries in a few nodes, on every node that was tried it fails...

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. The first step should always be enabling `debug` logging.
  * Open the file `/etc/rexray/config.yml`
  * Set the log level for both REX-Ray and libStorage to `debug` and enable
HTTP request and response tracing for libStorage:
```yaml
  libstorage:
    service: dobs
    integration:
      volume:
        operations:
          create:
            default:
              size: 1
          mount:
            preempt: true
          unmount:
            ignoreUsedCount: true
  dobs:
    token: ****
    region: fra1
    convertUnderscores: true

```
